### ISSUE TITLE
Allow backing with a database

### ISSUE THREAD

**Issue by drGrove** [drGrove/mtls-server#4]
Add support for a database to back the system

Databases: Postgres, SQLite3

Table: certs
* id
* subject (The requestor subject)
* host (The requestors hostname)
* expires (Timestamp of expiration)
* cert (The actual public certificate)
* revoked (boolean)

**Comment by scjudd** [comment]
Would it make sense to also save the GPG key fingerprint? This way we know exactly who each cert was issued to, since I could just as well put "Danny Grove" in my CSR.

**Comment by drGrove** [comment]
That could work. We do fully know who generated a CSR as they sign it with their PGP key and we verify it against our known internal trust db.

**Comment by scjudd** [comment]
Should we replace `subject` with `email`, and force that all CSRs include an email address in their subjectAlternativeNames? I'm unclear on the purpose of storing `subject`.
